/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gamification.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import gamification.model.BadgeInstance;
import gamification.model.BadgeInstanceModel;
import gamification.model.BadgeInstanceSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BadgeInstance service. Represents a row in the &quot;GM_BadgeInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link gamification.model.BadgeInstanceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BadgeInstanceImpl}.
 * </p>
 *
 * @author Sebastien Le Marchand
 * @see BadgeInstanceImpl
 * @see gamification.model.BadgeInstance
 * @see gamification.model.BadgeInstanceModel
 * @generated
 */
@JSON(strict = true)
public class BadgeInstanceModelImpl extends BaseModelImpl<BadgeInstance>
	implements BadgeInstanceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a badge instance model instance should use the {@link gamification.model.BadgeInstance} interface instead.
	 */
	public static final String TABLE_NAME = "GM_BadgeInstance";
	public static final Object[][] TABLE_COLUMNS = {
			{ "badgeInstanceId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "badgeName", Types.VARCHAR },
			{ "badgeLevel", Types.INTEGER },
			{ "data_", Types.CLOB }
		};
	public static final String TABLE_SQL_CREATE = "create table GM_BadgeInstance (badgeInstanceId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,badgeName VARCHAR(75) null,badgeLevel INTEGER,data_ TEXT null)";
	public static final String TABLE_SQL_DROP = "drop table GM_BadgeInstance";
	public static final String ORDER_BY_JPQL = " ORDER BY badgeInstance.userId ASC, badgeInstance.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GM_BadgeInstance.userId ASC, GM_BadgeInstance.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.gamification.model.BadgeInstance"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.gamification.model.BadgeInstance"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.gamification.model.BadgeInstance"),
			true);
	public static long BADGENAME_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;
	public static long CREATEDATE_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BadgeInstance toModel(BadgeInstanceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BadgeInstance model = new BadgeInstanceImpl();

		model.setBadgeInstanceId(soapModel.getBadgeInstanceId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setBadgeName(soapModel.getBadgeName());
		model.setBadgeLevel(soapModel.getBadgeLevel());
		model.setData(soapModel.getData());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BadgeInstance> toModels(BadgeInstanceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BadgeInstance> models = new ArrayList<BadgeInstance>(soapModels.length);

		for (BadgeInstanceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.gamification.model.BadgeInstance"));

	public BadgeInstanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _badgeInstanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBadgeInstanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _badgeInstanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BadgeInstance.class;
	}

	@Override
	public String getModelClassName() {
		return BadgeInstance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("badgeInstanceId", getBadgeInstanceId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("badgeName", getBadgeName());
		attributes.put("badgeLevel", getBadgeLevel());
		attributes.put("data", getData());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long badgeInstanceId = (Long)attributes.get("badgeInstanceId");

		if (badgeInstanceId != null) {
			setBadgeInstanceId(badgeInstanceId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String badgeName = (String)attributes.get("badgeName");

		if (badgeName != null) {
			setBadgeName(badgeName);
		}

		Integer badgeLevel = (Integer)attributes.get("badgeLevel");

		if (badgeLevel != null) {
			setBadgeLevel(badgeLevel);
		}

		String data = (String)attributes.get("data");

		if (data != null) {
			setData(data);
		}
	}

	@JSON
	@Override
	public long getBadgeInstanceId() {
		return _badgeInstanceId;
	}

	@Override
	public void setBadgeInstanceId(long badgeInstanceId) {
		_badgeInstanceId = badgeInstanceId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask = -1L;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getBadgeName() {
		if (_badgeName == null) {
			return StringPool.BLANK;
		}
		else {
			return _badgeName;
		}
	}

	@Override
	public void setBadgeName(String badgeName) {
		_columnBitmask |= BADGENAME_COLUMN_BITMASK;

		if (_originalBadgeName == null) {
			_originalBadgeName = _badgeName;
		}

		_badgeName = badgeName;
	}

	public String getOriginalBadgeName() {
		return GetterUtil.getString(_originalBadgeName);
	}

	@JSON
	@Override
	public int getBadgeLevel() {
		return _badgeLevel;
	}

	@Override
	public void setBadgeLevel(int badgeLevel) {
		_badgeLevel = badgeLevel;
	}

	@JSON
	@Override
	public String getData() {
		if (_data == null) {
			return StringPool.BLANK;
		}
		else {
			return _data;
		}
	}

	@Override
	public void setData(String data) {
		_data = data;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			BadgeInstance.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BadgeInstance toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BadgeInstance)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BadgeInstanceImpl badgeInstanceImpl = new BadgeInstanceImpl();

		badgeInstanceImpl.setBadgeInstanceId(getBadgeInstanceId());
		badgeInstanceImpl.setCompanyId(getCompanyId());
		badgeInstanceImpl.setUserId(getUserId());
		badgeInstanceImpl.setCreateDate(getCreateDate());
		badgeInstanceImpl.setModifiedDate(getModifiedDate());
		badgeInstanceImpl.setBadgeName(getBadgeName());
		badgeInstanceImpl.setBadgeLevel(getBadgeLevel());
		badgeInstanceImpl.setData(getData());

		badgeInstanceImpl.resetOriginalValues();

		return badgeInstanceImpl;
	}

	@Override
	public int compareTo(BadgeInstance badgeInstance) {
		int value = 0;

		if (getUserId() < badgeInstance.getUserId()) {
			value = -1;
		}
		else if (getUserId() > badgeInstance.getUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(),
				badgeInstance.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BadgeInstance)) {
			return false;
		}

		BadgeInstance badgeInstance = (BadgeInstance)obj;

		long primaryKey = badgeInstance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BadgeInstanceModelImpl badgeInstanceModelImpl = this;

		badgeInstanceModelImpl._originalUserId = badgeInstanceModelImpl._userId;

		badgeInstanceModelImpl._setOriginalUserId = false;

		badgeInstanceModelImpl._originalBadgeName = badgeInstanceModelImpl._badgeName;

		badgeInstanceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BadgeInstance> toCacheModel() {
		BadgeInstanceCacheModel badgeInstanceCacheModel = new BadgeInstanceCacheModel();

		badgeInstanceCacheModel.badgeInstanceId = getBadgeInstanceId();

		badgeInstanceCacheModel.companyId = getCompanyId();

		badgeInstanceCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			badgeInstanceCacheModel.createDate = createDate.getTime();
		}
		else {
			badgeInstanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			badgeInstanceCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			badgeInstanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		badgeInstanceCacheModel.badgeName = getBadgeName();

		String badgeName = badgeInstanceCacheModel.badgeName;

		if ((badgeName != null) && (badgeName.length() == 0)) {
			badgeInstanceCacheModel.badgeName = null;
		}

		badgeInstanceCacheModel.badgeLevel = getBadgeLevel();

		badgeInstanceCacheModel.data = getData();

		String data = badgeInstanceCacheModel.data;

		if ((data != null) && (data.length() == 0)) {
			badgeInstanceCacheModel.data = null;
		}

		return badgeInstanceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{badgeInstanceId=");
		sb.append(getBadgeInstanceId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", badgeName=");
		sb.append(getBadgeName());
		sb.append(", badgeLevel=");
		sb.append(getBadgeLevel());
		sb.append(", data=");
		sb.append(getData());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("gamification.model.BadgeInstance");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>badgeInstanceId</column-name><column-value><![CDATA[");
		sb.append(getBadgeInstanceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>badgeName</column-name><column-value><![CDATA[");
		sb.append(getBadgeName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>badgeLevel</column-name><column-value><![CDATA[");
		sb.append(getBadgeLevel());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data</column-name><column-value><![CDATA[");
		sb.append(getData());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BadgeInstance.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BadgeInstance.class
		};
	private long _badgeInstanceId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private Date _modifiedDate;
	private String _badgeName;
	private String _originalBadgeName;
	private int _badgeLevel;
	private String _data;
	private long _columnBitmask;
	private BadgeInstance _escapedModel;
}