/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package gamification.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import gamification.model.BadgeInstance;

import gamification.service.BadgeInstanceLocalServiceUtil;

/**
 * The extended model base implementation for the BadgeInstance service. Represents a row in the &quot;GM_BadgeInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BadgeInstanceImpl}.
 * </p>
 *
 * @author Sebastien Le Marchand
 * @see BadgeInstanceImpl
 * @see gamification.model.BadgeInstance
 * @generated
 */
public abstract class BadgeInstanceBaseImpl extends BadgeInstanceModelImpl
	implements BadgeInstance {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a badge instance model instance should use the {@link BadgeInstance} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BadgeInstanceLocalServiceUtil.addBadgeInstance(this);
		}
		else {
			BadgeInstanceLocalServiceUtil.updateBadgeInstance(this);
		}
	}
}